/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as NoticesIndexRouteImport } from './routes/notices/index'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices/$noticeId'
import { Route as ViolationsIndexRouteImport } from './routes/violations/index'
import { Route as ViolationsViolationIdRouteImport } from './routes/violations/$violationId'
import { Route as WarningsIndexRouteImport } from './routes/warnings/index'
import { Route as WarningsWarningIdRouteImport } from './routes/warnings/$warningId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/notices/$noticeId',
  path: '/notices/$noticeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsIndexRoute = ViolationsIndexRouteImport.update({
  id: '/violations/',
  path: '/violations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsViolationIdRoute = ViolationsViolationIdRouteImport.update({
  id: '/violations/$violationId',
  path: '/violations/$violationId',
  getParentRoute: () => rootRouteImport,
} as any)
const WarningsIndexRoute = WarningsIndexRouteImport.update({
  id: '/warnings/',
  path: '/warnings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarningsWarningIdRoute = WarningsWarningIdRouteImport.update({
  id: '/warnings/$warningId',
  path: '/warnings/$warningId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/review': typeof ReviewRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/violations/$violationId': typeof ViolationsViolationIdRoute
  '/warnings/$warningId': typeof WarningsWarningIdRoute
  '/notices/': typeof NoticesIndexRoute
  '/violations/': typeof ViolationsIndexRoute
  '/warnings/': typeof WarningsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/review': typeof ReviewRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/violations/$violationId': typeof ViolationsViolationIdRoute
  '/warnings/$warningId': typeof WarningsWarningIdRoute
  '/notices': typeof NoticesIndexRoute
  '/violations': typeof ViolationsIndexRoute
  '/warnings': typeof WarningsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/review': typeof ReviewRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/violations/$violationId': typeof ViolationsViolationIdRoute
  '/warnings/$warningId': typeof WarningsWarningIdRoute
  '/notices/': typeof NoticesIndexRoute
  '/violations/': typeof ViolationsIndexRoute
  '/warnings/': typeof WarningsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impact'
    | '/review'
    | '/notices/$noticeId'
    | '/violations/$violationId'
    | '/warnings/$warningId'
    | '/notices/'
    | '/violations/'
    | '/warnings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impact'
    | '/review'
    | '/notices/$noticeId'
    | '/violations/$violationId'
    | '/warnings/$warningId'
    | '/notices'
    | '/violations'
    | '/warnings'
  id:
    | '__root__'
    | '/'
    | '/impact'
    | '/review'
    | '/notices/$noticeId'
    | '/violations/$violationId'
    | '/warnings/$warningId'
    | '/notices/'
    | '/violations/'
    | '/warnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactRoute: typeof ImpactRoute
  ReviewRoute: typeof ReviewRoute
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
  ViolationsViolationIdRoute: typeof ViolationsViolationIdRoute
  WarningsWarningIdRoute: typeof WarningsWarningIdRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
  ViolationsIndexRoute: typeof ViolationsIndexRoute
  WarningsIndexRoute: typeof WarningsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/notices/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations/': {
      id: '/violations/'
      path: '/violations'
      fullPath: '/violations/'
      preLoaderRoute: typeof ViolationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations/$violationId': {
      id: '/violations/$violationId'
      path: '/violations/$violationId'
      fullPath: '/violations/$violationId'
      preLoaderRoute: typeof ViolationsViolationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warnings/': {
      id: '/warnings/'
      path: '/warnings'
      fullPath: '/warnings/'
      preLoaderRoute: typeof WarningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warnings/$warningId': {
      id: '/warnings/$warningId'
      path: '/warnings/$warningId'
      fullPath: '/warnings/$warningId'
      preLoaderRoute: typeof WarningsWarningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactRoute: ImpactRoute,
  ReviewRoute: ReviewRoute,
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
  ViolationsViolationIdRoute: ViolationsViolationIdRoute,
  WarningsWarningIdRoute: WarningsWarningIdRoute,
  NoticesIndexRoute: NoticesIndexRoute,
  ViolationsIndexRoute: ViolationsIndexRoute,
  WarningsIndexRoute: WarningsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
