import { agencyConfig, DEMO_FIGURE_NOTICE } from '@/data/agencyConfig';
import { formatAmount } from '@/lib/currency';
import { formatDate } from '@/lib/dates';
import type { Violation } from '@/types/envirobill';
import type { DemoNotice } from '@/types/envirobill-ui';

/**
 * The formatted notice document. Produced entirely client-side — no PDF library,
 * no server, no payment processor. Printing is browser print / save as PDF.
 */
export function PrintableNotice({
  notice,
  violation,
}: {
  notice: DemoNotice;
  violation: Violation | undefined;
}) {
  return (
    <div className="printable-notice rounded-2xl bg-white p-12 text-slate-900 shadow-2xl">
      <header className="flex items-start justify-between gap-8 border-b-2 border-slate-900 pb-6">
        <div>
          <p className="text-2xl font-bold tracking-tight">{agencyConfig.name}</p>
          <p className="text-base font-medium text-slate-700">{agencyConfig.department}</p>
          {agencyConfig.addressLines.map((line) => (
            <p key={line} className="text-sm text-slate-600">
              {line}
            </p>
          ))}
          <p className="mt-1 text-sm text-slate-600">{agencyConfig.contactLine}</p>
        </div>
        <div className="flex size-24 shrink-0 items-center justify-center rounded-full border-2 border-dashed border-slate-400 text-center text-[10px] font-semibold tracking-widest text-slate-500 uppercase">
          {agencyConfig.sealPlaceholderText}
        </div>
      </header>

      <h1 className="mt-8 text-center text-2xl font-bold tracking-widest uppercase">
        Notice of Violation and Assessment
      </h1>

      <dl className="mt-8 grid grid-cols-2 gap-x-8 gap-y-3 text-base">
        <Line label="Notice number" value={notice.id} />
        <Line label="Date of issue" value={formatDate(notice.sent_at ?? notice.last_touched_on)} />
        <Line label="Site" value={violation?.location ?? '—'} />
        <Line label="Violation type" value={violation?.violation_type ?? '—'} />
        <Line
          label="Date detected"
          value={violation ? formatDate(violation.detected_at) : '—'}
        />
        <Line label="Severity" value={violation?.severity ?? '—'} />
      </dl>

      <section className="mt-8">
        <h2 className="text-sm font-bold tracking-widest uppercase">Findings</h2>
        <p className="mt-2 text-base leading-relaxed">{violation?.description ?? '—'}</p>
      </section>

      <section className="mt-8 border-y-2 border-slate-900 py-6">
        <div className="flex items-baseline justify-between">
          <span className="text-sm font-bold tracking-widest uppercase">Amount assessed</span>
          <span className="text-3xl font-bold tabular-nums">{formatAmount(notice.amount)}</span>
        </div>
        <div className="mt-2 flex items-baseline justify-between text-base">
          <span className="font-semibold">Payment due by</span>
          <span>{formatDate(notice.due_date)}</span>
        </div>
      </section>

      <section className="mt-6">
        <h2 className="text-sm font-bold tracking-widest uppercase">Basis of assessment</h2>
        <p className="mt-2 text-base leading-relaxed">{notice.penalty_basis.text}</p>
      </section>

      <section className="mt-6">
        <h2 className="text-sm font-bold tracking-widest uppercase">How to pay</h2>
        <p className="mt-2 text-base leading-relaxed">
          Payment is accepted by cheque payable to {agencyConfig.name}, posted to the address
          above, or in person at the divisional office during business hours. Please quote notice
          number {notice.id} on all correspondence. No online payment facility is offered.
        </p>
      </section>

      <section className="mt-12 flex items-end justify-between gap-12">
        <div className="w-64">
          <div className="border-b border-slate-900" />
          <p className="mt-2 text-sm text-slate-600">Authorised officer</p>
        </div>
        <div className="w-48">
          <div className="border-b border-slate-900" />
          <p className="mt-2 text-sm text-slate-600">Date</p>
        </div>
      </section>

      <p className="mt-10 border-t border-slate-300 pt-4 text-xs text-slate-500">
        {DEMO_FIGURE_NOTICE} This document is generated by a demonstration system and is not a
        legal instrument.
      </p>
    </div>
  );
}

function Line({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs font-bold tracking-widest text-slate-500 uppercase">{label}</dt>
      <dd className="text-base capitalize">{value}</dd>
    </div>
  );
}
